- ros_topic_name: camera_1/color/camera_info
  gz_topic_name: /j100_0000/sensors/camera_1/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
